const actionType = {
    GET_USERS: "GET_USERS",
    SAVE_USERS: "SAVE_USERS",
    FAIL_REQUEST: "FAIL_REQUEST",
    SEND_FORM_DATA: "SEND_FORM_DATA",
    GET_COMPANY_HOST_DATA: "GET_COMPANY_HOST_DATA",
    SAVE_COMPANY_HOST_DATA: "SAVE_COMPANY_HOST_DATA",
    GET_COUNTRY_LIST: "GET_COUNTRY_LIST",
    SAVE_COUNTRY_LIST: "SAVE_COUNTRY_LIST",
    GET_TYPICODE_USERS: "GET_TYPICODE_USERS",
    SAVE_TYPICODE_USERS: "SAVE_TYPICODE_USERS",
    GET_TYPICODE_POST: "GET_TYPICODE_POST",
    SAVE_TYPICODE_POST: "SAVE_TYPICODE_POST",
    GET_TYPICODE_COMMENT: "GET_TYPICODE_COMMENT",
    SAVE_TYPICODE_COMMENT: "SAVE_TYPICODE_COMMENT",
};

export default actionType