const actionType = {
    GET_USERS: "GET_USERS",
    SAVE_USERS: "SAVE_USERS",
    FAIL_REQUEST: "FAIL_REQUEST",
    SEND_FORM_DATA: "SEND_FORM_DATA",
    GET_SERVER_DATA: "GET_SERVER_DATA",
    SAVE_SERVER_DATA: "SAVE_SERVER_DATA",
    GET_COUNTRY_LIST:"GET_COUNTRY_LIST",
    SAVE_COUNTRY_LIST:"SAVE_COUNTRY_LIST",
};

export default actionType